version: "3.9"
services:
  db:
    image: postgres:13.0-alpine
    container_name: virtual_accounts_db
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=VA_user
      - POSTGRES_PASSWORD=churpy#02
      - POSTGRES_DB=VA_db
    #   connecting to network called backend
    networks:
      - backend

  api:
    build:
      dockerfile: docker/Dockerfile
      context: .
      target: dev
    container_name: virtual_account_api
    restart: unless-stopped
    ports:
      - 8080:8080
    volumes:
      - ./:/app
    depends_on:
      - db
    #   connecting to same network as backend
    networks:
      - backend

volumes:
  postgres_data:

networks:
  backend:
    driver: bridge